server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ratingservice
    username: Priyanshu
    password: Priyanshu@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: Rating-Service

  config:
    import: optional:configserver:http://localhost:8085

jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka

